import React from 'react';

export type Language = 'es' | 'en';

export const TRANSLATIONS = {
  es: {
    home: 'Inicio',
    catalog: 'Catálogo',
    quote: 'Cotizar',
    admin: 'Admin',
    heroSub: 'SOLUCIONES DE MANUFACTURA ADITIVA',
    heroTitle1: 'Imprime todo',
    heroTitle2: 'en 3D',
    heroDesc: 'Servicios de impresión 3D premium para prototipado industrial y coleccionables de alta gama. Ingeniería de precisión, entrega global.',
    explore: 'Explorar Catálogo',
    customQuote: 'Cotización Personalizada',
    totalPrints: 'Impresiones Totales',
    materials: 'Materiales',
    activeGateways: 'Pasarelas Activas',
    globalShipping: 'Envío Global',
    statsLive: 'En Vivo',
    statsActive: 'Activo',
    curatedWorks: 'TRABAJOS SELECCIONADOS',
    featuredTitle1: 'Proyectos',
    featuredTitle2: 'Destacados',
    viewFullCatalog: 'Ver Catálogo Completo',
    cart: 'Tu Carrito',
    emptyCart: 'El carrito está vacío. Empieza a crear algo increíble.',
    summary: 'Resumen de Pago',
    subtotal: 'Subtotal',
    shipping: 'Envío',
    total: 'Total',
    processOrder: 'Procesar Orden',
    remove: 'Eliminar',
    quantity: 'Cantidad',
    askNova: 'Preguntar a Nova...',
    processing: 'Procesando...',
    freeGlobal: 'GLOBAL_GRATIS',
    catalogHeader: 'Catálogo de Impresiones',
    detailAdd: 'Agregar a la Orden',
    dropModel: 'Arrastra tu modelo 3D aquí',
    quoteDesc: 'Sube tu archivo .STL o .OBJ para obtener un presupuesto instantáneo basado en material y peso.',
    materialType: 'Tipo de Material',
    density: 'Densidad',
    estimatedCost: 'Costo Estimado',
    adminLogin: 'ACCESO OPERADOR',
    securedTerminal: 'Terminal de Seguridad Nova3D. Identificate para continuar.',
    authenticate: 'Verificar Identidad',
    management: 'Gestión de Sistema',
    vendor: 'Sección_Vendedor',
    uploadProduct: 'Cargar Nuevo Producto',
    orders: 'Pedidos',
    inventory: 'Inventario de Stock',
    terminate: 'Cerrar Sesión',
    uploadProject: 'Subir Nuevo Diseño',
    gatewayReady: 'SISTEMA_LISTO',
    projectName: 'Nombre del Producto',
    baseCost: 'Precio Unitario',
    projectDesc: 'Descripción del Producto',
    dropAssets: 'Arrastrá fotos desde tu PC',
    initProject: 'Inicializar Producto',
    recentSubmissions: 'Cargas Recientes',
    confirmed: 'Confirmado',
    pending: 'Pendiente',
    loading: 'Cargando...',
    login: 'Entrar',
    signup: 'Registrarse',
    logout: 'Logout',
    authRequired: 'AUTENTICACIÓN REQUERIDA',
    authDesc: 'Por favor, iniciá sesión para acceder a esta sección de la plataforma.',
    email: 'Correo electrónico',
    password: 'Contraseña',
    privacy: 'Protocolo_Privacidad',
    terms: 'Términos_Servicio',
    footerDesc: 'Sistemas de impresión 3D de grado industrial. Unimos el diseño digital con la realidad física con precisión aditiva.',
    account: 'Mi cuenta',
    wsConsult: 'Consultar por WhatsApp',
    wsMessage: 'Escribe tu mensaje...',
    wsSend: 'Enviar Mensaje',
    wsTitle: 'CONSULTA DE PRODUCTO',
    contact: 'Contacto',
    contactTitle: 'Protocolo de Contacto',
    contactSub: 'Establece una conexión directa con nuestra central de manufactura aditiva.',
    contactLoc: 'Localización_Física',
    contactWA: 'Conexión_WhatsApp',
    contactEmail: 'Canal_Electrónico',
    contactSend: 'Enviar Mensaje',
    contactFormName: 'Identificación',
    contactFormMsg: 'Mensaje / Consulta',
    contactBtn: 'INICIAR_WHATSAPP',
    contactNote: 'Al hacer clic en INICIAR_WHATSAPP, serás redirigido a la aplicación oficial para continuar la comunicación de forma segura.',
    searchPlaceholder: 'Buscar productos...',
    noProductsFound: 'No se encontraron productos',
    filters: 'Filtros',
    filterCategory: 'Categoría',
    filterColor: 'Color',
    filterSize: 'Tamaño',
    filterMaterial: 'Material',
    filterPrice: 'Precio',
    filterClear: 'Limpiar Filtros',
    filterReset: 'Reiniciar',
    all: 'Todos',
  },
  en: {
    home: 'Home',
    catalog: 'Catalog',
    quote: 'Quote',
    admin: 'Admin',
    heroSub: 'ADITIVE_MANUFACTURING_SOLUTIONS',
    heroTitle1: 'Print Everything',
    heroTitle2: 'in 3D',
    heroDesc: 'Premium 3D printing services for industrial prototyping and high-end collectibles. Engineered for precision, delivered globally.',
    explore: 'Explore Catalog',
    customQuote: 'Custom Quote',
    totalPrints: 'Total Prints',
    materials: 'Materials',
    activeGateways: 'Active Gateways',
    globalShipping: 'Global Shipping',
    statsLive: 'Live',
    statsActive: 'Active',
    curatedWorks: 'CURATED_WORKS',
    featuredTitle1: 'Featured',
    featuredTitle2: 'Projects',
    viewFullCatalog: 'View Full Catalog',
    cart: 'Your Cart',
    emptyCart: 'The cart is empty. Start creating something amazing.',
    summary: 'Payment Summary',
    subtotal: 'Subtotal',
    shipping: 'Shipping',
    total: 'Total',
    processOrder: 'Process Order',
    remove: 'Remove',
    quantity: 'Quantity',
    askNova: 'Ask Nova...',
    processing: 'Processing...',
    freeGlobal: 'FREE_GLOBAL',
    catalogHeader: 'Impressions Catalog',
    detailAdd: 'Add To Order',
    dropModel: 'Drop 3D Model Here',
    quoteDesc: 'Upload your .STL or .OBJ file to get an instant pricing estimate based on material and weight.',
    materialType: 'Material Type',
    density: 'Density',
    estimatedCost: 'Estimated Cost',
    adminLogin: 'ADMIN_LOGIN',
    securedTerminal: 'Secured Terminal Access. Authenticate to continue.',
    authenticate: 'Authenticate Identity',
    management: 'Management',
    vendor: 'Vendor Portal',
    uploadProduct: 'Upload Product',
    orders: 'Orders',
    inventory: 'Inventory',
    terminate: 'Terminate Session',
    uploadProject: 'Upload New Project',
    gatewayReady: 'GATEWAY_READY',
    projectName: 'Project Name',
    baseCost: 'Base Cost',
    projectDesc: 'Project Description',
    dropAssets: 'Drop High-Res Assets',
    initProject: 'Initialize Project',
    recentSubmissions: 'Recent Submissions',
    confirmed: 'Confirmed',
    pending: 'Pending',
    loading: 'Loading...',
    login: 'Login',
    signup: 'Sign Up',
    logout: 'Logout',
    authRequired: 'AUTHENTICATION_REQUIRED',
    authDesc: 'Please login to access this section of the platform.',
    email: 'Email Address',
    password: 'Password',
    privacy: 'Privacy_Protocol',
    terms: 'Service_Terms',
    footerDesc: 'Industrial grade 3D printing and rapid prototyping. We bridge the gap between digital design and physical reality with additive precision.',
    account: 'My Account',
    wsConsult: 'Consult via WhatsApp',
    wsMessage: 'Type your message...',
    wsSend: 'Send Message',
    wsTitle: 'PRODUCT CONSULTATION',
    contact: 'Contact',
    contactTitle: 'Contact Protocol',
    contactSub: 'Establish a direct connection with our additive manufacturing center.',
    contactLoc: 'Physical_Location',
    contactWA: 'WhatsApp_Connection',
    contactEmail: 'Electronic_Channel',
    contactSend: 'Send Message',
    contactFormName: 'Identification',
    contactFormMsg: 'Message / Inquiry',
    contactBtn: 'START_WHATSAPP',
    contactNote: 'By clicking START_WHATSAPP, you will be redirected to the official application to continue communication securely.',
    searchPlaceholder: 'Search products...',
    noProductsFound: 'No products found',
    filters: 'Filters',
    filterCategory: 'Category',
    filterColor: 'Color',
    filterSize: 'Size',
    filterMaterial: 'Material',
    filterPrice: 'Price',
    filterClear: 'Clear Filters',
    filterReset: 'Reset',
    all: 'All',
  }
};

export const AppContext = React.createContext<{
  lang: Language;
  setLang: (l: Language) => void;
  theme: 'dark' | 'light';
  setTheme: (t: 'dark' | 'light') => void;
  t: typeof TRANSLATIONS['en'];
}>({
  lang: 'es',
  setLang: () => {},
  theme: 'dark',
  setTheme: () => {},
  t: TRANSLATIONS['es']
});
